import Head from "next/head";

//I import the different components I need to use
import Navbar from "../components/Navbar";
import FormDownload from "../components/FormDownload";
import Disclaimer from "../components/Disclaimer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <FormDownload />
      <Disclaimer />
    </div>
  );
}
